### ISSUE TITLE
unrecognized dbms option: mysql

### ISSUE THREAD

**Issue by ghost** [osdldbt/dbt2#2]
Hi

I'm trying to test MySQL performance.

I ran the following:
cmake -H. -Bbuilds/release -DDBMS=mysql

But when I run dbt2-run-workload, I receive an error in my results/client log. dbt2 client doesn't seem to be built with mysql support.

dbt2-client -a mysql
unrecognized dbms option: mysql

How do I build the project with mysql support?

**Comment by markwkm** [comment]
The mysql support is going to need some TLC...

The mysql client libraries need to be installed and pkg-config should pick them up when running cmake (or using make with Makefile.cmake).

I think the scripts are going to need a good amount of updating.  I think all of the mysql scripts work with old versions of mysql because of the command line argument changes over the years.

I should be able to help identify what the scripts are supposed to do, but I will need help on the mysql specific parts...

**Comment by markwkm** [comment]
I've done some minimal clean up in the scripts for the v0.61.5 release and got a 1-tier test to work with MySQL 8.0.  That makes me confident that the C code is still in good shape.  Running through all the other configuration options will take time.

I'm honestly not sure how to handle this since I believe the original contributors and maintainers to this part of the code has moved on.  What I am thinking of doing is to close this issue, and if there are more problems, maybe we can slowly work through them as they come up.
