### ISSUE TITLE
Data post process failure

### ISSUE THREAD

**Issue by kemparaju** [osdldbt/dbt2#5]
After running the workload using dbt2-driver3, while processing the data sometimes I see the below error

CMD:
`find ./runs -name  'mix*.log' | xargs dbt2-post-process`

Error
`============  =====  =========  =========  ===========  ===========  =====
          ..     ..    Response Time (s)            ..           ..     ..
------------  -----  --------------------  -----------  -----------  -----
 Transaction      %   Average     90th %        Total    Rollbacks      %
============  =====  =========  =========  ===========  ===========  =====
(standard_in) 1: syntax error
============  =====  =========  =========  ===========  ===========  =====

* Throughput: 0.00 new-order transactions per minute (NOTPM)
* Duration: -43.9 minute(s)
* Unknown Errors: 0
* Ramp Up Time: 61.0 minute(s)`

**Comment by markwkm** [comment]
Can you upload the entire results directory somewhere and I can try to see if the issue is obvious.  Also, which commit/release of the code are you using?

**Comment by kemparaju** [comment]
[runs.zip](https://github.com/osdldbt/dbt2/files/11515343/runs.zip)
Attached the results directory. Though the attached folder is not for the above results, but it also produces same syntax error.

I'm currently using release [dbt2-0.51.0](https://github.com/osdldbt/dbt2/releases/tag/v0.51.0)

**Comment by markwkm** [comment]
I think I understand what happened.  Based on additional information from another email exchange, the post processing script simply doesn't handle the case when no transactions were actually executed for any of the transaction.

The log files confirm that the driver threw no errors and recorded the transaction mix correctly.  The test parameters were specified such that there are no New Order transactions execute.

So the bug that needs to be fixed is properly reporting when there are no transactions run.  Otherwise it appears the test ran correctly.

**Comment by markwkm** [comment]
Fixed here: https://github.com/osdldbt/dbt2/commit/962b7676f29fa66ae94242215bfe16348b7b1fd6
